#------------------------------------------------------------------------------

CFLAGS= -std=c++11 -lpthread
CC=g++

#------------------------------------------------------------------------------

all: p1 p2 p3a p3b

### 

p1: p1.cpp
	$(CC) -o p1 p1.cpp $(CFLAGS)

p2: p2.cpp
	$(CC) -o p2 p2.cpp $(CFLAGS)

p3a: p3a.cpp
	$(CC) -o p3a p3a.cpp $(CFLAGS)

p3b: p3b.cpp
	$(CC) -o p3b p3b.cpp $(CFLAGS)

clean:

	rm -f p1

###


