#------------------------------------------------------------------------------

CFLAGS= -std=c++11
CC=g++

#------------------------------------------------------------------------------

all: p1a p1b p3 p4

###

p1a: p1a.o
	$(CC) -o p1a p1a.o 

p1a.o: p1a.cpp 
	$(CC) -c $(CFLAGS) p1a.cpp

###

p1b: p1b.o
	$(CC) -o p1b p1b.o 

p1b.o: p1b.cpp 
	$(CC) -c $(CFLAGS) p1b.cpp

###

p3: p3.o
	$(CC) -o p3 p3.o 

p3.o: p3.cpp 
	$(CC) -c $(CFLAGS) p3.cpp

###

p4: p4.o
	$(CC) -o p4 p4.o 

p4.o: p4.cpp 
	$(CC) -c $(CFLAGS) p4.cpp



